
ALTER TABLE public.model_guides 
  ADD COLUMN IF NOT EXISTS type TEXT NOT NULL DEFAULT 'image',
  ADD COLUMN IF NOT EXISTS icon_url TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS video_preview_url TEXT NOT NULL DEFAULT '';
