-- Edit Image tool — wired to Nano Banana 2 via the generate-image pipeline
INSERT INTO public.tools (
  slug, route, input_type, icon_name, active, featured,
  title_en, title_ar,
  description_en, description_ar,
  short_desc_en, short_desc_ar,
  hero_title_en, hero_title_ar,
  hero_subtitle_en, hero_subtitle_ar,
  cover_image_url,
  provider_name, provider_endpoint,
  default_credit_cost, internal_provider_cost_estimate,
  result_type, sort_order,
  tool_mode, selected_model_id,
  default_prompt_en, default_prompt_ar,
  cta_label_en, cta_label_ar,
  upload_label_en, upload_label_ar,
  upload_helper_en, upload_helper_ar,
  requires_upload, auto_run, prompt_hidden
) VALUES (
  'edit-image', '/tools/edit-image', 'mixed', 'Wand2', true, true,
  'Edit Image', 'تعديل الصورة',
  'Transform and edit your images with AI-powered precision using Nano Banana 2',
  'حوّل صورك وعدّلها بدقة مدعومة بالذكاء الاصطناعي باستخدام Nano Banana 2',
  'AI-powered image editing', 'تعديل الصور بالذكاء الاصطناعي',
  'Edit your images with precision', 'عدّل صورك بدقة احترافية',
  'Powered by Nano Banana 2', 'مدعوم بـ Nano Banana 2',
  '',
  'Fal.ai', 'fal-ai/nano-banana-2',
  10, 0.08,
  'image', 15,
  'edit_image', '582df12f-1c11-4abe-beaf-9905cd8f1d47',
  '', '',
  'Edit Image', 'تعديل الصورة',
  'Drop your image here or click to upload', 'أسقط صورتك هنا أو انقر للرفع',
  'JPG, PNG, WEBP up to 10MB', 'JPG, PNG, WEBP حتى ١٠ ميغابايت',
  true, false, false
)
ON CONFLICT (slug) DO UPDATE SET
  route = EXCLUDED.route,
  input_type = EXCLUDED.input_type,
  icon_name = EXCLUDED.icon_name,
  active = EXCLUDED.active,
  featured = EXCLUDED.featured,
  title_en = EXCLUDED.title_en,
  title_ar = EXCLUDED.title_ar,
  description_en = EXCLUDED.description_en,
  description_ar = EXCLUDED.description_ar,
  short_desc_en = EXCLUDED.short_desc_en,
  short_desc_ar = EXCLUDED.short_desc_ar,
  hero_title_en = EXCLUDED.hero_title_en,
  hero_title_ar = EXCLUDED.hero_title_ar,
  hero_subtitle_en = EXCLUDED.hero_subtitle_en,
  hero_subtitle_ar = EXCLUDED.hero_subtitle_ar,
  provider_name = EXCLUDED.provider_name,
  provider_endpoint = EXCLUDED.provider_endpoint,
  default_credit_cost = EXCLUDED.default_credit_cost,
  internal_provider_cost_estimate = EXCLUDED.internal_provider_cost_estimate,
  result_type = EXCLUDED.result_type,
  tool_mode = EXCLUDED.tool_mode,
  selected_model_id = EXCLUDED.selected_model_id,
  cta_label_en = EXCLUDED.cta_label_en,
  cta_label_ar = EXCLUDED.cta_label_ar,
  upload_label_en = EXCLUDED.upload_label_en,
  upload_label_ar = EXCLUDED.upload_label_ar,
  upload_helper_en = EXCLUDED.upload_helper_en,
  upload_helper_ar = EXCLUDED.upload_helper_ar,
  requires_upload = EXCLUDED.requires_upload,
  updated_at = now();