// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

export const supabaseConfigMissing = !SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

type NoopResult = {
  data: unknown;
  error: null;
};

function createNoopQueryBuilder() {
  const result: NoopResult = { data: [], error: null };
  const builder: Record<string, unknown> = {};
  const chain = () => builder;

  [
    'select',
    'insert',
    'update',
    'upsert',
    'delete',
    'eq',
    'neq',
    'gt',
    'gte',
    'lt',
    'lte',
    'in',
    'is',
    'not',
    'or',
    'filter',
    'like',
    'ilike',
    'match',
    'contains',
    'containedBy',
    'textSearch',
    'startsWith',
    'range',
    'order',
    'limit',
  ].forEach((method) => {
    builder[method] = chain;
  });

  builder.single = () => {
    result.data = null;
    return builder;
  };
  builder.maybeSingle = () => {
    result.data = null;
    return builder;
  };

  builder.then = (resolve: (value: NoopResult) => unknown, reject?: (reason: unknown) => unknown) =>
    Promise.resolve(result).then(resolve, reject);

  return builder;
}

function createNoopSupabaseClient() {
  const subscription = { unsubscribe: () => undefined };
  const channel = {
    on: () => channel,
    subscribe: () => channel,
    unsubscribe: () => Promise.resolve('ok'),
  };
  const notConfiguredError = { message: 'Supabase is not configured.' };

  return {
    from: () => createNoopQueryBuilder(),
    channel: () => channel,
    removeChannel: () => Promise.resolve('ok'),
    auth: {
      onAuthStateChange: () => ({ data: { subscription } }),
      getSession: () => Promise.resolve({ data: { session: null }, error: null }),
      getUser: () => Promise.resolve({ data: { user: null }, error: null }),
      signOut: () => Promise.resolve({ error: null }),
      signInWithOAuth: () => Promise.resolve({ data: null, error: notConfiguredError }),
      signInWithPassword: () => Promise.resolve({ data: { user: null, session: null }, error: notConfiguredError }),
      signUp: () => Promise.resolve({ data: { user: null, session: null }, error: notConfiguredError }),
      resetPasswordForEmail: () => Promise.resolve({ data: null, error: notConfiguredError }),
      updateUser: () => Promise.resolve({ data: { user: null }, error: notConfiguredError }),
    },
    functions: {
      invoke: () => Promise.resolve({ data: { success: false, error: 'platform_not_configured' }, error: notConfiguredError }),
    },
    storage: {
      from: () => ({
        upload: () => Promise.resolve({ data: null, error: notConfiguredError }),
        getPublicUrl: () => ({ data: { publicUrl: '' } }),
      }),
    },
  } as unknown as SupabaseClient<Database>;
}

export const supabase = supabaseConfigMissing
  ? createNoopSupabaseClient()
  : createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: typeof window !== 'undefined' ? window.localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    },
  });
